project:
  type: website
  # pre-render: prepare.py # Doesn't really work anymore...?
  render:
    - index.md
    - "Demonstrations/!(2024)"
    - "Notebooks/*"
    - "ThePythonTutorial/*.*"
    - googlec027a6a2057eb177.html
    

website:
  title: "UQ PUG"
  description: "UQ Python User Group"
  favicon: "python-logo-only.svg"
  image: "python-logo_only.svg"
  navbar:
    search: true
    left:
      - text: "About us"
        href: index.md
      - text: "UQ Library Technology Training"
        href: https://uqlibrary.github.io/technology-training/
      - text: "Other User Groups"
        menu:
          - text: "UQ R User Group"
            href: https://uqrug.netlify.app/
  sidebar:
    collapse-level: 1
    contents: 
      - section: "Monthly PUGs"
        contents: Notebooks/*
      - section: "The Python Tutorial"
        contents: ThePythonTutorial/*.*
      - section: "Demonstrations"
        contents: Demonstrations/**/*
      - section: "Archives"
        contents: Notebooks/Archive/*/*
    

format:
  html:
    theme: 
      - default
      - custom.scss
    toc: true
